// <auto-generated />
using System;
using APIEscolaArabe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolaArabeApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221109020244_Dependencias")]
    partial class Dependencias
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("APIEscolaArabe.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Matricula")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<int?>("aulaId")
                        .HasColumnType("int");

                    b.Property<int?>("enderecoId")
                        .HasColumnType("int");

                    b.Property<int?>("modalidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("aulaId");

                    b.HasIndex("enderecoId");

                    b.HasIndex("modalidadeId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("APIEscolaArabe.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("HorarioAula")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("APIEscolaArabe.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("APIEscolaArabe.Models.Modalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DiasSemana")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HorarioAula")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeCurso")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeProf")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("APIEscolaArabe.Models.Aluno", b =>
                {
                    b.HasOne("APIEscolaArabe.Models.Aula", "aula")
                        .WithMany()
                        .HasForeignKey("aulaId");

                    b.HasOne("APIEscolaArabe.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoId");

                    b.HasOne("APIEscolaArabe.Models.Modalidade", "modalidade")
                        .WithMany()
                        .HasForeignKey("modalidadeId");

                    b.Navigation("aula");

                    b.Navigation("endereco");

                    b.Navigation("modalidade");
                });
#pragma warning restore 612, 618
        }
    }
}
